apiVersion: v1
kind: Service
metadata:
  name: api-go-auth-service
  namespace: fargate-backend
  labels:
    app: api-go-auth-app
spec:
  selector:
    app: api-go-auth-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080